server:
  port: 8080
  tomcat:
    threads:
      max: 500
      min-spare: 50
    accept-count: 500
    max-connections: 10000
    connection-timeout: 5000

spring:
  application:
    name: seckill-system

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/seckill?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: seckill
    password: seckill123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      connection-timeout: 3000

  data:
    redis:
      # ========== Sentinel 模式（高可用） ==========
      host: 127.0.0.1
      port: 6380
      lettuce:
        pool:
          max-active: 100
          max-idle: 30
          min-idle: 10
          max-wait: 3000ms

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update

  jackson:
    time-zone: Asia/Shanghai

  task:
    scheduling:
      pool:
        size: 4

logging:
  level:
    root: info

webauthn:
  rp-id: localhost
  rp-name: 秒杀系统
  origin: http://localhost:5173